/* File-backed portals.
   A portal anyone can open with no account and no database, so the product can
   be shown to a prospect, a board, or a client team without provisioning
   anything. Two of them today:

     /demo    the anonymised sample portal — every section is illustrative.
     /paact   the PAACT engagement. Scope & timeline is that engagement's own
              content; the other four sections carry the anonymised sample, so
              the client can see the shape of what is coming. Which is which is
              declared, not implied: see `sampleSections` below.

   It is the same application in both: the same five sections, the same
   scoping, the same workplan interactions. Only the store is different. Edits
   live in memory and vanish on reload, which the banner says plainly rather
   than letting someone believe they saved something.

   /demo is also the fallback for a deploy with no Supabase project configured,
   so a fresh Netlify site shows the product instead of an error. */

export const DEMO_SLUG = 'demo';
export const PAACT_SLUG = 'paact';

/* Every section of the product, in order. The same list both portals show. */
const ALL = ['scope', 'plan', 'findings', 'workplan', 'dashboard'];

/* ---------- the shared shape ----------
   One place where a data file becomes the portal record the app reads.
   supabase/seed.mjs writes the same { phases, scope, firm } object into the
   `engagement` jsonb, so a portal that moves to the database keeps this shape
   rather than needing a second adapter. */

function filePortal({ id, slug, client, engagement, plan, findings, sections, sampleSections, sampleClient }) {
  return {
    id,
    slug,
    client_name: client.name,
    place: client.place,
    engagement_name: client.engagement,
    /* Null, not undefined, when nothing has been adopted: Plan.jsx prints
       "Adopted {date}." for any truthy value. */
    adopted: client.adopted || null,
    brand: {},
    labels: {},
    /* Which sections this portal SHOWS, in order. Defaults to all five; a
       portal passes fewer when fewer exist yet. Settings writes this field, so
       turning one on later is a click rather than a deploy. */
    sections: sections && sections.length ? sections : ALL,
    engagement,
    plan: {
      vision: plan.vision,
      framing: plan.framing,
      priorities: plan.priorities,
      track: plan.track,
    },
    findings,
    /* WHOSE the borrowed sections are. The sample is a whole other
       organisation's plan, and the masthead wears this name while you are
       reading them, so the identity on screen always matches the content
       under it rather than putting this client's name over someone else's
       priorities. Absent on a portal that borrows nothing. */
    sampleClient,
    /* Which of the five sections are illustrative rather than this client's
       own. The app marks these; a section not listed here is real content.
       Stated as data because the honest answer differs per portal, and a
       strategic plan showing priorities a client never agreed to is worse than
       no plan at all. */
    sampleSections,
  };
}

function fileTasks(rows) {
  /* Guarded: a portal whose workplan has not been built yet carries no tasks,
     and the portal has to render anyway. */
  return (rows || []).map((t, i) => ({
    id: t.id,
    parent: t.parent || null,
    init: t.obj,
    title: t.title,
    owner: t.owner || '',
    start: t.start || '',
    due: t.due || '',
    // The prototype carried a pseudo-status for a task that was merely late.
    // Late is derived from the due date; it is never stored.
    status: t.status === 'late' ? 'next' : t.status,
    note: '',
    position: i,
  }));
}

/* ---------- /demo ----------
   ANONYMISED content, generated by scripts/make-demo.mjs. This is served on a
   public URL with no sign-in, so it must never be a real client's discovery
   data — those are 933 candid congregation responses, and what identifies them
   is the organisation. A separate chunk too: findings alone is ~320 KB, and a
   signed-in client portal must never pay for data it will not use. */
export async function loadDemo() {
  const [{ PORTAL }, { FINDINGS }] = await Promise.all([
    import('../../clients/demo/plan.js'),
    import('../../clients/demo/findings.js'),
  ]);

  const portal = filePortal({
    id: 'demo',
    slug: DEMO_SLUG,
    client: PORTAL.client,
    engagement: { phases: PORTAL.phases, scope: PORTAL.scope, firm: PORTAL.firm },
    plan: PORTAL.plan,
    findings: FINDINGS,
    /* All five: there is no real client anywhere in this portal. */
    sampleSections: ALL,
  });

  /* The demo is dated content — phases, due dates and "past due" only read
     correctly relative to the engagement it describes, so the clock is pinned
     rather than letting the whole plan drift into the past. This pin is the
     ONLY one left: a real client's portal reads the real date (see loadPaact). */
  return { portal, tasks: fileTasks(PORTAL.tasks), now: PORTAL.today, role: DEMO_ROLE };
}

/* ---------- /paact ----------
   Real engagement, real names, and a kickoff in the room. Section 1 is PAACT's
   own scope and timeline, from clients/paact/plan.js. It carries no other
   anonymised sample above, because PAACT has no plan, findings or workplan yet
   — they are the OUTPUT of the engagement section 1 describes. Three chunks so
   a database-backed portal still pays for none of it. */
export async function loadPaact() {
  const { PORTAL: PAACT } = await import('../../clients/paact/plan.js');

  const portal = filePortal({
    id: 'paact',
    slug: PAACT_SLUG,
    client: PAACT.client,
    engagement: paactEngagement(PAACT),
    /* NOTHING BORROWED. This portal used to fill its other four sections with
       another engagement's anonymised plan, findings and workplan, marked as
       samples, so the client could see the shape of what was coming. It did
       that job and it is over: the sample is somebody else's content, and the
       moment a portal is the client's real workspace rather than a pitch, a
       page of another organisation's priorities under their masthead is a
       liability with no upside. */
    plan: { vision: '', framing: '', priorities: [], track: null },
    findings: { themes: [], responses: [] },
    /* ONE SECTION, because one section is what exists. The plan, the findings
       and the workplan are OUTPUTS of the engagement section one describes —
       the findings close in November, the plan is drafted in January, the
       implementation roadmap is a phase 4 deliverable. Each is switched on from
       Settings on the day it has something in it. An empty tab a client clicks
       into and finds nothing in is worse than a tab that is not there yet. */
    sections: ['scope'],
  });

  /* No pinned clock: `now: null` and App.jsx reads the real local date. This
     workspace is contract deliverable #4 and PAACT runs their plan in it for
     seventeen months, so a frozen date is not a snapshot — it is a sentence
     that is wrong every day after the one it was written on. */
  return { portal, tasks: [], now: null, role: DEMO_ROLE };
}

/* The brief's vocabulary -> the app's, in one function, so
   clients/paact/plan.js can stay the brief verbatim and can be pushed into the
   Supabase `engagement` jsonb without a second translation to keep in step.
   Nothing here adds a fact; it renames and derives. */
const PHASE_STATUS = { in_progress: 'active', complete: 'done', done: 'done', not_started: '' };

function paactEngagement(src) {
  const phases = (src.phases || []).map((p) => ({
    ...p,
    /* Panel state key and React list key. Derived from the phase number rather
       than the array index, because Phase 4's dates are expected to move and an
       index key would reopen the wrong panel when the order changes. */
    id: `p${p.number}`,
    n: p.number, // the strip and the rail print "Phase {n}"
    blurb: p.purpose, // display alias; `purpose` stays beside it
    /* 'active' is the only "you are here" the app knows, and '' is how it
       spells not-started. Left unmapped, no phase is active and the portal
       tells the room the engagement is in its final phase. */
    status: PHASE_STATUS[p.status] || '',
  }));

  const scope = { ...(src.scope || {}) };

  /* Display aliases for the cadence panel's two-line rows. The brief gives a
     rhythm, an activity and an owner, and no dates — there is no next
     occurrence to print, so none is invented. */
  scope.cadence = (src.scope?.cadence || []).map((c) => ({
    ...c,
    label: c.rhythm,
    detail: c.owner ? `${c.what} · ${c.owner}` : c.what,
  }));

  /* One flat list beside the three real groups, for a panel that expects a
     single `team` array. `side` is explicit: the older panel inferred
     consultant-vs-client by matching the org string against the firm name,
     which files Alan — HTI team, different org name — with the client. */
  scope.team = [
    ...(src.scope?.consultingTeam || []).map((m) => ({ ...m, side: 'Consultant' })),
    ...(src.scope?.clientTeam || []).map((m) => ({ ...m, side: 'Client' })),
  ];

  /* convener, location, planHorizon and the engagement dates ride alongside
     phases/scope/firm, which is where the rail and masthead look. */
  return { phases, scope, firm: src.firm, ...(src.meta || {}) };
}

/* ---------- the registry ----------
   Which slugs the app can serve from files. App.jsx consults this before the
   database, so a future database portal whose slug is literally 'paact' would
   be shadowed by the file: when PAACT moves to Supabase, delete the entry and
   seed clients/paact/plan.js instead. */
export const FILE_PORTALS = {
  [DEMO_SLUG]: loadDemo,
  [PAACT_SLUG]: loadPaact,
};

/* The file-backed portal that serves this slug, or null if none does.
   `unconfigured: true` — a deploy with no Supabase project — makes /demo the
   answer for every slug, which is how a fresh Netlify site shows the product
   instead of an error. */
export function fileBackedSlug(slug, { unconfigured = false } = {}) {
  const s = String(slug || '').toLowerCase();
  if (Object.prototype.hasOwnProperty.call(FILE_PORTALS, s)) return s;
  return unconfigured ? DEMO_SLUG : null;
}

/* Load one. Resolves to { portal, tasks, now, role }, or to null when no file
   portal serves the slug. `now` pins the clock for a portal whose content is
   dated — only /demo does — and is null for a live engagement, which is how
   App.jsx knows to use the real local date. */
export function loadFilePortal(slug, opts) {
  const s = fileBackedSlug(slug, opts);
  return s ? FILE_PORTALS[s]() : Promise.resolve(null);
}

/* Owner, so a file portal shows the whole product — including the plan editor,
   which is what makes this a tool rather than a document. Nothing persists, so
   there is nothing to protect: the store's write calls no-op without a Supabase
   project, and every change dies with the tab. */
export const DEMO_ROLE = 'owner';
