/* Demo mode.
   A portal anyone can open — no account, no database — so the product can be
   shown to a prospect, a board, or a friend without provisioning anything.

   It is the same application: the same five sections, the same scoping, the
   same workplan interactions. Only the store is different. Edits live in
   memory and vanish on reload, which the banner says plainly rather than
   letting someone believe they saved something.

   It is also the fallback for a deploy with no Supabase project configured, so
   a fresh Netlify site shows the product instead of an error. */

export const DEMO_SLUG = 'demo';

/* ANONYMISED content, generated by scripts/make-demo.mjs. This is served on a
   public URL with no sign-in, so it must never be a real client's discovery
   data — those are 933 candid congregation responses, and what identifies them
   is the organisation. A separate chunk too: findings alone is ~320 KB, and a
   signed-in client portal must never pay for data it will not use. */
export async function loadDemo() {
  const [{ PORTAL }, { FINDINGS }] = await Promise.all([
    import('../../data/demo-plan.js'),
    import('../../data/demo-findings.js'),
  ]);

  const portal = {
    id: 'demo',
    slug: DEMO_SLUG,
    client_name: PORTAL.client.name,
    place: PORTAL.client.place,
    engagement_name: PORTAL.client.engagement,
    adopted: PORTAL.client.adopted,
    brand: {},
    labels: {},
    sections: ['scope', 'plan', 'findings', 'workplan', 'dashboard'],
    engagement: { phases: PORTAL.phases, scope: PORTAL.scope, firm: PORTAL.firm },
    plan: {
      vision: PORTAL.plan.vision,
      framing: PORTAL.plan.framing,
      priorities: PORTAL.plan.priorities,
      track: PORTAL.plan.track,
    },
    findings: FINDINGS,
  };

  const tasks = PORTAL.tasks.map((t, i) => ({
    id: t.id,
    parent: t.parent || null,
    init: t.obj,
    title: t.title,
    owner: t.owner || '',
    start: t.start || '',
    due: t.due || '',
    // The prototype carried a pseudo-status for a task that was merely late.
    // Late is derived from the due date; it is never stored.
    status: t.status === 'late' ? 'next' : t.status,
    note: '',
    position: i,
  }));

  /* The demo is dated content — phases, due dates and "past due" only read
     correctly relative to the engagement it describes, so the clock is pinned
     rather than letting the whole plan drift into the past. */
  return { portal, tasks, now: PORTAL.today };
}

/* Staff, so every interaction in the workplan can be demonstrated. Nothing
   persists, so there is nothing to protect. */
export const DEMO_ROLE = 'staff';
