#!/usr/bin/env node
/* Netlify build. Copies the portal into public/ and fills data/config.js from
   the site's environment.

   SUPABASE_URL and SUPABASE_ANON_KEY are public by design — the browser needs
   both to sign in, and they are meant to ship in the page. The service-role key
   is NOT read here and must never reach the client.
   (Same reasoning as the Impact Suite's SECRETS_SCAN_OMIT_KEYS note.) */
import fs from 'node:fs';
import path from 'node:path';

const root = path.resolve(import.meta.dirname, '..');
const out = path.join(root, 'public');

const SLUG = process.env.PORTAL_SLUG || 'resonate';
const URL_ = (process.env.SUPABASE_URL || process.env.SUPABASE_PROJECT_URL || '').replace(/\/+$/, '');
const KEY = process.env.SUPABASE_ANON_KEY || process.env.SUPABASE_PUBLISHABLE_KEY || '';

fs.rmSync(out, { recursive: true, force: true });
fs.mkdirSync(path.join(out, 'data'), { recursive: true });

fs.copyFileSync(path.join(root, 'index.html'), path.join(out, 'index.html'));
for (const f of ['findings.js', 'plan.js']) {
  fs.copyFileSync(path.join(root, 'data', f), path.join(out, 'data', f));
}

fs.writeFileSync(
  path.join(out, 'data', 'config.js'),
  '/* generated by scripts/build-portal.mjs — do not edit */\n' +
    'window.SPP_CONFIG = ' +
    JSON.stringify({ supabaseUrl: URL_, supabaseAnonKey: KEY, portalSlug: SLUG }, null, 2) +
    ';\n',
);

const mode = URL_ && KEY ? 'Supabase accounts' : 'NO SUPABASE — the portal will fall back to browser-local storage';
console.log(`built public/ for portal "${SLUG}" · ${mode}`);
if (!URL_ || !KEY) {
  console.log('  set SUPABASE_URL and SUPABASE_ANON_KEY on this Netlify site to enable sign-in');
}
