#!/usr/bin/env node
/* Writes supabase/clients/<slug>.sql: a client's whole portal as ONE paste
   into the Supabase SQL editor.

     node scripts/client-sql.mjs paact

   Why SQL rather than `npm run seed`: the person setting a client up should
   not need a terminal, and the SQL editor already runs as an administrator, so
   no key is created, shared or stored. Why GENERATED: the content's source of
   truth before go-live is clients/<slug>/plan.js, and a hand-copied SQL file is
   a second copy that drifts. CI regenerates this and fails on any difference.

   What it carries: the portal row (who it is for, which sections show) and the
   engagement document — section 01 — in the canonical shape from
   lib/engagement.js, plus the first owner. Not plans, findings or workplans:
   those are produced during an engagement and are edited in the app.

   The generated file never overwrites anything. A portal that already exists
   keeps every edit made in the app; an owner whose role was changed in the app
   keeps that role. Running it twice is the same as running it once. */

import fs from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { engagementOfFile, tidy, validate } from '../src/lib/engagement.js';

const root = path.resolve(import.meta.dirname, '..');
const slug = String(process.argv[2] || '').toLowerCase();
/* The first owner: the person who runs the paste. Everyone else is added from
   the app's Access screen once this person can sign in. */
const OWNER = 'alan@goodworkatlanta.co';

if (!/^[a-z0-9-]+$/.test(slug)) {
  console.error('Usage: node scripts/client-sql.mjs <slug>   (the folder name under clients/)');
  process.exit(1);
}
const file = path.join(root, 'clients', slug, 'plan.js');
if (!fs.existsSync(file)) {
  console.error(`No ${path.relative(root, file)}. Client content lives in clients/<slug>/plan.js.`);
  process.exit(1);
}
const { PORTAL: P } = await import(pathToFileURL(file).href);

const engagement = tidy(engagementOfFile(P));
const problems = validate(engagement);
if (problems.length) {
  console.error(`clients/${slug}/plan.js would load a broken timeline:\n - ${problems.join('\n - ')}`);
  process.exit(1);
}
if (P.plan || P.tasks) {
  console.warn(`note: clients/${slug}/plan.js also has a plan or a workplan. Neither is in the SQL — this file sets up section 01. Load the rest with npm run seed.`);
}

const lit = (s) => (s == null || s === '' ? 'null' : `'${String(s).replace(/'/g, "''")}'`);
const json = JSON.stringify(engagement, null, 2);
const TAG = '$engagement$';
if (json.includes(TAG)) throw new Error(`the content contains ${TAG}, which would end the SQL quote early`);

const client = P.client || {};
const sql = `-- ${client.name || slug} — the whole portal, in one paste.
--
-- GENERATED from clients/${slug}/plan.js by \`node scripts/client-sql.mjs ${slug}\`.
-- Do not edit this file by hand: change the client file and regenerate. CI
-- fails if the two disagree.
--
-- HOW TO USE IT
--   Supabase -> SQL Editor -> New query. Paste ALL of this file. Press Run.
--   Run supabase/schema.sql first, once; this file needs its tables.
--
-- WHAT IT DOES
--   1. Creates the /${slug} portal with section 01 (scope & timeline) filled in.
--   2. Makes ${OWNER} its owner. That account must already exist; if
--      it does not, nothing is created and the message says what to do.
--
-- SAFE TO RUN AGAIN. If the portal already exists, its content is not touched:
-- anything edited in the app since is kept. An owner whose access was changed
-- in the app keeps that change.

do $$
declare
  v_owner_email text := ${lit(OWNER)};
  v_slug        constant text := ${lit(slug)};
  v_tenant      constant text := ${lit(slug)};
  v_portal      uuid;
  v_user        uuid;
  v_tag         text;
  v_engagement  constant jsonb := ${TAG}
${json}
${TAG};
begin
  -- The account first, so a missing one stops the paste before anything exists.
  select id, coalesce(raw_app_meta_data ->> 'gw_tenant', '')
    into v_user, v_tag
    from auth.users where lower(email) = lower(v_owner_email);
  if v_user is null then
    raise exception 'No account for % in this Supabase project. Nothing was created. Make it in Authentication -> Users -> Add user -> Create new user (any password, tick Auto Confirm User), then run this again.', v_owner_email;
  end if;

  insert into portals (slug, tenant, client_name, place, engagement_name, sections, engagement)
  values (v_slug, v_tenant, ${lit(client.name)}, ${lit(client.place)}, ${lit(client.engagement)},
          '["scope"]'::jsonb, v_engagement)
  on conflict (slug) do nothing
  returning id into v_portal;

  if v_portal is null then
    select id into v_portal from portals where slug = v_slug;
    -- Created earlier but EMPTY (by bootstrap.sql, say): fill it. Anything
    -- with content in it is left exactly as it is.
    update portals set engagement = v_engagement
     where id = v_portal and engagement = '{}'::jsonb;
    update portals set sections = '["scope"]'::jsonb
     where id = v_portal and sections = '[]'::jsonb;
    raise notice 'Portal /% already existed. Its content was left as it is.', v_slug;
  else
    raise notice 'Portal /% created.', v_slug;
  end if;

  -- The tag that decides which clients an account can reach at all. An
  -- untagged account is tagged for this client only; "*" (your own firm,
  -- every client) is never given out here.
  if v_tag = '' then
    update auth.users
       set raw_app_meta_data = coalesce(raw_app_meta_data, '{}'::jsonb)
                               || jsonb_build_object('gw_tenant', v_tenant, 'gw_role', 'viewer')
     where id = v_user;
    raise notice '% was untagged; tagged gw_tenant = %.', v_owner_email, v_tenant;
  elsif v_tag <> '*' and lower(v_tag) <> v_tenant then
    raise warning '% is tagged gw_tenant = "%", so it will NOT see /%. Tag it "*" (your own firm) or "%".', v_owner_email, v_tag, v_slug, v_tenant;
  end if;

  insert into portal_members (portal_id, user_id, email, role)
  values (v_portal, v_user, lower(v_owner_email), 'owner')
  on conflict (portal_id, user_id) do nothing;

  raise notice 'Done. % can sign in and open /%.', v_owner_email, v_slug;
end $$;

-- What you should see below: the portal, how many phases it has, and who can
-- open it. A tag of * or ${slug} is right; anything else will not see the portal.
select p.slug as portal,
       jsonb_array_length(p.engagement -> 'phases') as phases,
       m.email as person,
       m.role,
       coalesce(u.raw_app_meta_data ->> 'gw_tenant', '(none)') as tag
  from portals p
  join portal_members m on m.portal_id = p.id
  join auth.users u on u.id = m.user_id
 where p.slug = ${lit(slug)}
 order by m.role, m.email;
`;

const outDir = path.join(root, 'supabase', 'clients');
fs.mkdirSync(outDir, { recursive: true });
const out = path.join(outDir, `${slug}.sql`);
fs.writeFileSync(out, sql);
console.log(`wrote ${path.relative(root, out)} — ${engagement.phases.length} phases, ${engagement.phases.reduce((n, p) => n + p.deliverables.length, 0)} deliverables`);
