#!/usr/bin/env node
/* Builds the anonymised demo dataset.

   The demo is served on a public URL with no sign-in, so it must not carry a
   real client's discovery data. The source material here is 933 verbatim
   congregation responses — candid ones, including criticism of named leaders
   and views on contested questions. They were collected anonymously and they
   stay that way: what identifies them is the ORGANISATION, so this replaces
   the organisation, the neighbourhood, and every named person with fictional
   equivalents, and leaves the analysis intact.

   Generic church vocabulary ("Life Group", "elders") is deliberately kept —
   thousands of churches use it, it identifies nobody, and stripping it would
   make the demo read like a redaction.

     node scripts/make-demo.mjs

   Writes data/demo-plan.js and data/demo-findings.js. The real data/plan.js
   and data/findings.js stay put, for seeding that client's own portal. */

import fs from 'node:fs';
import path from 'node:path';

const root = path.resolve(import.meta.dirname, '..');
const dataDir = path.join(root, 'data');

/* The client's name is also an ordinary English verb, and "doesn't seem to
   resonate" must not become "doesn't seem to Northside". So verb uses are
   parked behind a sentinel, the organisation is replaced case-insensitively
   (people write "attending resonate" in lowercase all the time), and the verbs
   are put back afterwards. */
const VERB_FORMS = /\bresonat(?:es|ed|ing)\b/gi;
const VERB_BASE =
  /\b((?:to|really|truly|clearly|not|does\s?n[o']?t|do\s?n[o']?t|did\s?n[o']?t|would|will|might|may|can|could|should)\s+)resonate\b/gi;

/* Order matters: longer phrases before the bare neighbourhood name. \b keeps
   "Chris" from touching "Christ", "Christian" or "Christmas" — the single most
   dangerous replacement in a church dataset, so it stays case-SENSITIVE. */
const RULES = [
  [/\bBelvedere\s+Plaza\b/gi, 'Cedar Hollow Plaza'],
  [/\bBelvedere\s+Park\b/gi, 'Cedar Hollow'],
  [/\bBelvedere\b/gi, 'Cedar Hollow'],
  [/\bresonate['\u2019]s\b/gi, 'Northside\u2019s'],
  [/\bresonate\b/gi, 'Northside'],
  [/\bChris['\u2019]s\b/g, 'Dale\u2019s'],
  [/\bChris\b/g, 'Dale'],
  [/\bNoah['\u2019]s\b/g, 'Owen\u2019s'],
  [/\bNoah\b/g, 'Owen'],
  [/\bSarah['\u2019]s\b/g, 'Priya\u2019s'],
  [/\bSarah\b/g, 'Priya'],
  [/\bDecatur\b/gi, 'Ashford'],
  [/\bClarkston\b/gi, 'Fairview'],
  [/\bStone\s+Mountain\b/gi, 'Granite Ridge'],
  [/\bDe\s?Kalb\b/gi, 'Weston County'],
  [/\bTucker\b/g, 'Halston'],
];

function scrubString(str) {
  const parked = [];
  const park = (m) => `\u0001${parked.push(m) - 1}\u0001`;
  let s = str.replace(VERB_FORMS, park).replace(VERB_BASE, (_m, lead) => lead + park('resonate'));
  s = RULES.reduce((acc, [re, to]) => acc.replace(re, to), s);
  return s.replace(/\u0001(\d+)\u0001/g, (_m, i) => parked[+i]);
}

function scrub(value) {
  if (typeof value === 'string') return scrubString(value);
  if (Array.isArray(value)) return value.map(scrub);
  if (value && typeof value === 'object') {
    return Object.fromEntries(Object.entries(value).map(([k, v]) => [k, scrub(v)]));
  }
  return value;
}

const { PORTAL } = await import(path.join(dataDir, 'plan.js'));
const { FINDINGS } = await import(path.join(dataDir, 'findings.js'));

const demoPortal = scrub(PORTAL);
demoPortal.client = {
  ...demoPortal.client,
  name: 'Northside Community Church',
  place: 'Cedar Hollow · Atlanta, GA',
};

const demoFindings = scrub(FINDINGS);

const header = (what) =>
  `/* ${what}\n` +
  `   ANONYMISED. Generated by scripts/make-demo.mjs — do not edit by hand.\n` +
  `   Served publicly with no sign-in, so it carries no real client's data:\n` +
  `   the organisation, neighbourhood and every named person are fictional.\n` +
  `   The analysis, counts and structure are real, which is what the demo is\n` +
  `   meant to show. */\n`;

fs.writeFileSync(
  path.join(dataDir, 'demo-plan.js'),
  header('Demo engagement, plan and workplan.') + 'export const PORTAL = ' + JSON.stringify(demoPortal, null, 1) + ';\n',
);
fs.writeFileSync(
  path.join(dataDir, 'demo-findings.js'),
  header('Demo discovery findings.') + 'export const FINDINGS = ' + JSON.stringify(demoFindings) + ';\n',
);

/* Fail loudly rather than shipping a leak: assert nothing identifying survived. */
const out = fs.readFileSync(path.join(dataDir, 'demo-plan.js'), 'utf8') +
            fs.readFileSync(path.join(dataDir, 'demo-findings.js'), 'utf8');

/* The verb survives on purpose, so strip verb uses before looking for leaks —
   anything still matching is the organisation's name. */
const forCheck = out.replace(VERB_FORMS, 'X').replace(VERB_BASE, '$1X');
const BANNED = [/\bresonate\b/i, /\bBelvedere\b/i, /\bChris\b/, /\bNoah\b/, /\bSarah\b/, /\bDecatur\b/i, /\bClarkston\b/i, /\bStone\s+Mountain\b/i, /\bDe\s?Kalb\b/i];
const leaks = BANNED.filter((re) => re.test(forCheck)).map((re) => re.source);

console.log(`demo-plan.js      ${demoPortal.plan.priorities.length} priorities · ${demoPortal.tasks.length} rows`);
console.log(`demo-findings.js  ${demoFindings.themes.length} themes · ${demoFindings.quotes.length} responses`);
console.log(`preserved on purpose: "Life Group" ${(out.match(/Life\s?Group/gi) || []).length}×, "elder" ${(out.match(/\belder/gi) || []).length}×`);

if (leaks.length) {
  console.error('\nREFUSING: identifying terms survived scrubbing: ' + leaks.join(', '));
  process.exit(1);
}
console.log('\nclean — no identifying terms remain');
