-- PAACT (Promise All Atlanta Children Thrive) — the whole portal, in one paste.
--
-- GENERATED from clients/paact/plan.js by `node scripts/client-sql.mjs paact`.
-- Do not edit this file by hand: change the client file and regenerate. CI
-- fails if the two disagree.
--
-- HOW TO USE IT
--   Supabase -> SQL Editor -> New query. Paste ALL of this file. Press Run.
--   Run supabase/schema.sql first, once; this file needs its tables.
--
-- WHAT IT DOES
--   1. Creates the /paact portal with section 01 (scope & timeline) filled in.
--   2. Makes alan@goodworkatlanta.co its owner. That account must already exist; if
--      it does not, nothing is created and the message says what to do.
--
-- SAFE TO RUN AGAIN. If the portal already exists, its content is not touched:
-- anything edited in the app since is kept. An owner whose access was changed
-- in the app keeps that change.

do $$
declare
  v_owner_email text := 'alan@goodworkatlanta.co';
  v_slug        constant text := 'paact';
  v_tenant      constant text := 'paact';
  v_portal      uuid;
  v_user        uuid;
  v_tag         text;
  v_engagement  constant jsonb := $engagement$
{
  "firm": {
    "name": "HTI Catalysts",
    "lead": "Dr. Folami Prescott-Adams",
    "analyst": "Alan Maxcy"
  },
  "convener": "GEEARS",
  "location": "Atlanta, GA",
  "planHorizon": "3–5 years",
  "engagementStart": "2026-09-01",
  "engagementEnd": "2027-02-15",
  "phases": [
    {
      "id": "p1",
      "number": 1,
      "name": "Foundation",
      "start": "2026-09-01",
      "end": "2026-09-30",
      "status": "in_progress",
      "purpose": "Build the relationship, agree the approach, and get the team reading before anyone is interviewed.",
      "note": "First PAACT-facing session is Sept 23 at 3400 Peachtree Rd. Everything before that is internal prep.",
      "deliverables": [
        {
          "id": "p1-d1",
          "name": "Internal HTI kickoff (Sept 9)",
          "done": true
        },
        {
          "id": "p1-d2",
          "name": "Weekly check-in with Shawnell established",
          "done": false
        },
        {
          "id": "p1-d3",
          "name": "Strategic planning kickoff session with PAACT team (Sept 23, in person)",
          "done": false
        },
        {
          "id": "p1-d4",
          "name": "Document library assembled and shared",
          "done": false
        },
        {
          "id": "p1-d5",
          "name": "Listening session #1 at GEEARS Fall Luncheon (Sept 17)",
          "done": true
        },
        {
          "id": "p1-d6",
          "name": "Interview and focus group protocols drafted",
          "done": false
        },
        {
          "id": "p1-d7",
          "name": "Purpose assigned to each convening and SPT meeting",
          "done": false
        }
      ]
    },
    {
      "id": "p2",
      "number": 2,
      "name": "Discovery",
      "start": "2026-09-15",
      "end": "2026-12-18",
      "status": "not_started",
      "purpose": "Listen widely enough that no one can say the plan came from one room.",
      "note": "No stakeholder-facing work 18 Dec 2026 – 3 Jan 2027.",
      "deliverables": [
        {
          "id": "p2-d1",
          "name": "Stakeholder interviews (up to 20)",
          "done": false
        },
        {
          "id": "p2-d2",
          "name": "Focus groups: Advisory Board, providers, parents and ambassadors, civic leaders",
          "done": false
        },
        {
          "id": "p2-d3",
          "name": "Listening sessions at existing gatherings (4)",
          "done": false
        },
        {
          "id": "p2-d4",
          "name": "SWOT/SOAR webform launched and closed (target 60+ responses)",
          "done": false
        },
        {
          "id": "p2-d5",
          "name": "Partner convening #1: landscape and collective SWOT",
          "done": false
        },
        {
          "id": "p2-d6",
          "name": "Partner convening #2: role, vision, and impact",
          "done": false
        },
        {
          "id": "p2-d7",
          "name": "Partner convening #3: naming what matters (priorities)",
          "done": false
        },
        {
          "id": "p2-d8",
          "name": "Knowledge-sharing workshops with PAACT staff (up to 3)",
          "done": false
        },
        {
          "id": "p2-d9",
          "name": "Peer collective impact calls: Cobb, Detroit, Memphis, Colorado",
          "done": false
        },
        {
          "id": "p2-d10",
          "name": "Quantitative data pull from Danielle's dashboard and Readiness Radar",
          "done": false
        }
      ]
    },
    {
      "id": "p3",
      "number": 3,
      "name": "Synthesis",
      "start": "2026-11-02",
      "end": "2027-01-16",
      "status": "not_started",
      "purpose": "Turn everything we heard into something partners can recognize themselves in.",
      "note": "Rachel reviews for inclusivity before findings go out: all voices represented, not just the loudest.",
      "deliverables": [
        {
          "id": "p3-d1",
          "name": "Ecosystem scan brief",
          "done": false
        },
        {
          "id": "p3-d2",
          "name": "Analysis tracker: every input tagged by question cluster",
          "done": false
        },
        {
          "id": "p3-d3",
          "name": "Impact Report integrated (arrives Nov 2026)",
          "done": false
        },
        {
          "id": "p3-d4",
          "name": "Strategic Planning Team meetings (6 hours across 3 sessions)",
          "done": false
        },
        {
          "id": "p3-d5",
          "name": "Findings summary (draft)",
          "done": false
        },
        {
          "id": "p3-d6",
          "name": "Draft vision, mission, and long-term impact goals",
          "done": false
        },
        {
          "id": "p3-d7",
          "name": "Draft priorities with objectives",
          "done": false
        },
        {
          "id": "p3-d8",
          "name": "Findings presentation deck",
          "done": false
        }
      ]
    },
    {
      "id": "p4",
      "number": 4,
      "name": "Plan design",
      "start": "2027-01-19",
      "end": "2027-02-13",
      "status": "not_started",
      "purpose": "Test the synthesis in public, then write the plan.",
      "note": "Draft review cycle is the gap in the current HTI Catalysts workplan. Findings and draft need to move earlier or the final presentation moves to March.",
      "deliverables": [
        {
          "id": "p4-d1",
          "name": "Presentation of findings to all stakeholder groups (convening #4)",
          "done": false
        },
        {
          "id": "p4-d2",
          "name": "Draft strategic plan to PAACT core team for review",
          "done": false
        },
        {
          "id": "p4-d3",
          "name": "Consolidated feedback received",
          "done": false
        },
        {
          "id": "p4-d4",
          "name": "Recommendations: governance, partner engagement, sustainability, measurement",
          "done": false
        },
        {
          "id": "p4-d5",
          "name": "Implementation roadmap with owners, timelines, milestones",
          "done": false
        },
        {
          "id": "p4-d6",
          "name": "Two-page visual summary",
          "done": false
        },
        {
          "id": "p4-d7",
          "name": "Full plan, digital and print-ready",
          "done": false
        },
        {
          "id": "p4-d8",
          "name": "Social media and presentation asset set",
          "done": false
        }
      ]
    },
    {
      "id": "p5",
      "number": 5,
      "name": "Adoption & implementation",
      "start": "2027-02-15",
      "end": "2028-02-15",
      "status": "not_started",
      "purpose": "Hand PAACT a plan it can run, not a document it can file.",
      "note": "The HTI Catalysts engagement closes Feb 15, 2027. Year one of the plan runs to Feb 2028. This workspace is deliverable #4 of the contract.",
      "deliverables": [
        {
          "id": "p5-d1",
          "name": "Final plan presentation and celebration (co-facilitated with PAACT)",
          "done": false
        },
        {
          "id": "p5-d2",
          "name": "Project management workspace live with owners and milestones",
          "done": false
        },
        {
          "id": "p5-d3",
          "name": "Workspace training for PAACT staff (90 min)",
          "done": false
        },
        {
          "id": "p5-d4",
          "name": "Close-out report",
          "done": false
        },
        {
          "id": "p5-d5",
          "name": "90-day check: workspace in active use",
          "done": false
        },
        {
          "id": "p5-d6",
          "name": "Year one progress review",
          "done": false
        }
      ]
    }
  ],
  "scope": {
    "scopeSummary": "Design and facilitate a participatory strategic planning process resulting in a 3–5 year plan for the PAACT collaborative, with implementation roadmap and live project management workspace.",
    "inScope": [
      "Up to 4 partner convenings (2–3 hrs each)",
      "Up to 4 kickoff-phase workshops with PAACT staff",
      "Up to 20 stakeholder interviews",
      "4 focus groups (60–90 min)",
      "4 listening sessions at existing gatherings",
      "6 hours of Strategic Planning Team meetings",
      "Document and data review, SWOT and SOAR analysis",
      "Findings presentation",
      "Final plan in four formats plus workspace and training",
      "Close-out report"
    ],
    "outOfScope": [
      "Implementation support after Feb 15, 2027 (unless contracted separately)",
      "Primary data collection beyond the engagement counts above",
      "Evaluation of PAACT programs (Danielle Wallace holds that role)"
    ],
    "outcomes": [
      "A shared understanding of Atlanta's early childhood landscape and systems",
      "A collective SWOT analysis informed by partner and community voice",
      "Recommendations for governance, partnership engagement, and backbone infrastructure",
      "A strategic plan document outlining priority strategies, objectives, and measurable outcomes for the next 3–5 years",
      "An implementation roadmap with timelines, roles, and resource considerations",
      "A clear and inspiring vision, mission, and long-term impact goals for PAACT"
    ],
    "questions": [
      "What is PAACT's unique role and value within Atlanta's early childhood ecosystem?",
      "What outcomes should we hold ourselves collectively accountable for over the next 3–5 years?",
      "How should PAACT measure collective impact and progress toward shared goals?",
      "How can PAACT strengthen alignment and collaboration across partners where alliance members have shared ownership?",
      "What is the long-term vision for PAACT's role within GEEARS and the Atlanta early childhood landscape?",
      "How do we meaningfully include providers and families with lived experience in governance and strategy?",
      "What policy and systems priorities should PAACT champion locally?",
      "How do we deepen partnerships with the City of Atlanta and philanthropic partners?",
      "What backbone infrastructure and capacity does PAACT need to sustain and grow its work?",
      "How does PAACT remain responsive to community needs and emerging opportunities?"
    ],
    "documents": [
      "PAACT Final Report",
      "GEEARS Strategic Plan (Section 3)",
      "PAACT Overview slide deck",
      "Ambassador Research Report",
      "Evaluation of the Repair and Renovation Program",
      "Impact Report (ready November 2026)",
      "List of centers that received renovation funds — Danielle Wallace",
      "Spreadsheet of Ambassadors — Dawan"
    ],
    "cadence": [
      {
        "id": "c1",
        "rhythm": "Weekly",
        "what": "30-min check-in with Shawnell",
        "owner": "Dr. Prescott-Adams",
        "next": ""
      },
      {
        "id": "c2",
        "rhythm": "Weekly",
        "what": "Internal HTI Catalysts team sync",
        "owner": "Dr. Prescott-Adams",
        "next": ""
      },
      {
        "id": "c3",
        "rhythm": "Biweekly",
        "what": "Written update to PAACT: done, next, need",
        "owner": "Alan",
        "next": ""
      },
      {
        "id": "c4",
        "rhythm": "Monthly",
        "what": "GEEARS leadership touchpoint",
        "owner": "Dr. Prescott-Adams",
        "next": ""
      },
      {
        "id": "c5",
        "rhythm": "Quarterly",
        "what": "Advisory Board meeting (align focus group and listening session)",
        "owner": "PAACT",
        "next": ""
      }
    ],
    "keyDates": [
      {
        "id": "k1",
        "date": "2026-09-17",
        "what": "GEEARS Fall Luncheon (listening session #1)"
      },
      {
        "id": "k2",
        "date": "2026-09-23",
        "what": "Strategic planning kickoff with PAACT team, in person"
      },
      {
        "id": "k3",
        "date": "2026-10-05",
        "what": "SWOT/SOAR webform launch (target)"
      },
      {
        "id": "k4",
        "date": "2026-11-13",
        "what": "SWOT/SOAR webform close (target)"
      },
      {
        "id": "k5",
        "date": "2026-11-30",
        "what": "Impact Report expected"
      },
      {
        "id": "k6",
        "date": "2026-12-18",
        "what": "Stakeholder engagement closes"
      },
      {
        "id": "k7",
        "date": "2027-01-16",
        "what": "Findings synthesis complete"
      },
      {
        "id": "k8",
        "date": "2027-02-15",
        "what": "RFP project end date"
      }
    ],
    "consultingTeam": [
      {
        "id": "ct1",
        "name": "Dr. Folami Prescott-Adams",
        "org": "",
        "role": "Engagement lead, facilitator",
        "owns": "Client relationship, all convenings and interviews, final presentation"
      },
      {
        "id": "ct2",
        "name": "Gina Glymph",
        "org": "",
        "role": "Co-facilitator",
        "owns": "Convenings, interviews, focus groups, listening sessions"
      },
      {
        "id": "ct3",
        "name": "Rachel Alterman Wallack",
        "org": "",
        "role": "Advisor",
        "owns": "ToP facilitation design, inclusivity review of instruments and findings"
      },
      {
        "id": "ct4",
        "name": "Alan Maxcy",
        "org": "",
        "role": "Analyst and writer",
        "owns": "Document review, SWOT/SOAR, synthesis, findings, plan document, four formats, workspace, close-out report"
      }
    ],
    "clientTeam": [
      {
        "id": "cl1",
        "name": "Shawnell",
        "org": "PAACT",
        "role": "Director, primary contact",
        "owns": "Weekly check-in, interview introductions, approvals"
      },
      {
        "id": "cl2",
        "name": "Eshe",
        "org": "PAACT",
        "role": "Staff, Advisory Board member",
        "owns": "Advisory Board coordination"
      },
      {
        "id": "cl3",
        "name": "Dawan",
        "org": "PAACT",
        "role": "Staff",
        "owns": "Ambassador and family recruitment, ambassador spreadsheet"
      },
      {
        "id": "cl4",
        "name": "Kristin Bernhard",
        "org": "GEEARS",
        "role": "Executive leadership",
        "owns": "GEEARS alignment, board access"
      },
      {
        "id": "cl5",
        "name": "Danielle Wallace",
        "org": "Evaluator (contract)",
        "role": "Data partner",
        "owns": "Provider dashboard, renovation center list"
      }
    ],
    "governance": [
      {
        "id": "g1",
        "body": "Strategic Planning Team",
        "members": "Subset of PAACT staff and members (roster TBD Sept 23)",
        "meets": "3 sessions, 2 hrs each, Nov–Jan"
      },
      {
        "id": "g2",
        "body": "PAACT Advisory Board",
        "members": "20 members",
        "meets": "Quarterly"
      },
      {
        "id": "g3",
        "body": "GEEARS Board",
        "members": "Full board",
        "meets": "15-min group interview at a scheduled meeting"
      }
    ]
  }
}
$engagement$;
begin
  -- The account first, so a missing one stops the paste before anything exists.
  select id, coalesce(raw_app_meta_data ->> 'gw_tenant', '')
    into v_user, v_tag
    from auth.users where lower(email) = lower(v_owner_email);
  if v_user is null then
    raise exception 'No account for % in this Supabase project. Nothing was created. Make it in Authentication -> Users -> Add user -> Create new user (any password, tick Auto Confirm User), then run this again.', v_owner_email;
  end if;

  insert into portals (slug, tenant, client_name, place, engagement_name, sections, engagement)
  values (v_slug, v_tenant, 'PAACT (Promise All Atlanta Children Thrive)', 'GEEARS · Atlanta, GA', 'Strategic Plan 2027–2031',
          '["scope"]'::jsonb, v_engagement)
  on conflict (slug) do nothing
  returning id into v_portal;

  if v_portal is null then
    select id into v_portal from portals where slug = v_slug;
    -- Created earlier but EMPTY (by bootstrap.sql, say): fill it. Anything
    -- with content in it is left exactly as it is.
    update portals set engagement = v_engagement
     where id = v_portal and engagement = '{}'::jsonb;
    update portals set sections = '["scope"]'::jsonb
     where id = v_portal and sections = '[]'::jsonb;
    raise notice 'Portal /% already existed. Its content was left as it is.', v_slug;
  else
    raise notice 'Portal /% created.', v_slug;
  end if;

  -- The tag that decides which clients an account can reach at all. An
  -- untagged account is tagged for this client only; "*" (your own firm,
  -- every client) is never given out here.
  if v_tag = '' then
    update auth.users
       set raw_app_meta_data = coalesce(raw_app_meta_data, '{}'::jsonb)
                               || jsonb_build_object('gw_tenant', v_tenant, 'gw_role', 'viewer')
     where id = v_user;
    raise notice '% was untagged; tagged gw_tenant = %.', v_owner_email, v_tenant;
  elsif v_tag <> '*' and lower(v_tag) <> v_tenant then
    raise warning '% is tagged gw_tenant = "%", so it will NOT see /%. Tag it "*" (your own firm) or "%".', v_owner_email, v_tag, v_slug, v_tenant;
  end if;

  insert into portal_members (portal_id, user_id, email, role)
  values (v_portal, v_user, lower(v_owner_email), 'owner')
  on conflict (portal_id, user_id) do nothing;

  raise notice 'Done. % can sign in and open /%.', v_owner_email, v_slug;
end $$;

-- What you should see below: the portal, how many phases it has, and who can
-- open it. A tag of * or paact is right; anything else will not see the portal.
select p.slug as portal,
       jsonb_array_length(p.engagement -> 'phases') as phases,
       m.email as person,
       m.role,
       coalesce(u.raw_app_meta_data ->> 'gw_tenant', '(none)') as tag
  from portals p
  join portal_members m on m.portal_id = p.id
  join auth.users u on u.id = m.user_id
 where p.slug = 'paact'
 order by m.role, m.email;
